#created on: 05/06/2013
package com.hernsys.rules

import com.hernsys.*

#list any import classes here.



#declare any global variables here




rule "expense greater than 1000"
    when
        customer : Customer( expense > 1000 );
    then
        System.out.println("The customer "  + customer.getName() + " has spent greater than 1.000 euros.");
  		customer.setDiscount(customer.getDiscount() + customer.getExpense()*5/100);

end

rule "Customer registered"
 	when
	  customer : Customer( registered == true )
 	then 
  	  System.out.println("The customer "  + customer.getName() + " is registered.");
      customer.setDiscount(customer.getDiscount() + customer.getExpense()*5/100);
end
